name: Terraform
main: com.cocoapebbles.terraform.Main
version: 1.0
api-version: 1.13
commands:
   tf:
      description: Allows you to interact with social media
      usage: "Type '/twitter help' to see available commands"
      permission: twitter
permissions:
  tf:
    description: Allows twitter command(s)
    default: true